export const NEWS_FETCHED_SUCCESSED = "NEWS_FETCHED_SUCCESSED";
export const NEWS_FETCHED_FAILED = "NEWS_FETCHED_FAILED";
export const NEWS_FETCHED_REQUESTED = "NEWS_FETCH_REQUESTED";
export const NEWS_FETCHED_PROGRESSED = "NEWS_FETCH_PROGRESSED";
export const NEWS_WARNING = "There is no news yet";
export const IS_AUTH_MODAL_OPEN = "IS_AUTH_MODAL_OPEN";
export const TOOGLE_MODAL = "TOOGLE_MODAL";
